import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/contexts/ThemeProvider";
import Navbar from "@/components/layout/Navbar";
import QueryClientWrapper from "@/Providers/QueryClientWrapper";
import GoogleAuthWrapper from "@/Providers/GoogleAuthWrapper";

export const metadata: Metadata = {
  title: "Valyarions",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <ThemeProvider >
          <QueryClientWrapper>
            <GoogleAuthWrapper>
              <UserProvider>
                <Navbar />
                {children}
              </UserProvider>
            </GoogleAuthWrapper>
          </QueryClientWrapper>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
