import type { Metadata } from "next";
import "./globals.css";
import { UserProvider } from "@/contexts/UserContext";
import { GoogleOAuthProvider } from "@react-oauth/google"; // Import the provider
import { Toaster } from "@/components/ui/toaster";
import { ThemeProvider } from "@/contexts/ThemeProvider";

import Navbar from "@/components/layout/Navbar";

export const metadata: Metadata = {
  title: "Valyarions",
  description: "Generated by create next app",
};
const googleClientId: string =
  process.env.NEXT_PUBLIC_GOOGLE_CLIENT_ID ||
  "298361459600-pe2mfqhml6qpji740893fke4r7646kh3.apps.googleusercontent.com"; // Store the client ID in .env

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <GoogleOAuthProvider clientId={googleClientId}>
          <UserProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <Navbar />
              {children}
            </ThemeProvider>
          </UserProvider>
        </GoogleOAuthProvider>
        <Toaster />
      </body>
    </html>
  );
}
